require("which-key").setup({
  preset = "helix",
  delay = 300,
  spec = {
    { "<leader>b", group = "buffer" },
    { "<leader>c", group = "code" },
    { "<leader>d", group = "debug" },
    { "<leader>f", group = "file/find" },
    { "<leader>g", group = "git" },
    { "<leader>gh", group = "hunks" },
    { "<leader>s", group = "search" },
    { "<leader>u", group = "ui" },
    { "<leader>w", group = "windows" },
    { "<leader><tab>", group = "tabs" },
    { "<leader>q", group = "quit/session" },
    { "g", group = "goto" },
    { "]", group = "next" },
    { "[", group = "prev" },
  },
})
